### ISSUE TITLE
Subject prefix to use

### ISSUE THREAD

**Issue by peaveyman** [tdobrovolskij/sanguinews#35]
If the subject prefix is left as is in the sanguinews.conf file, what does sanguinews use as the subject? Will it use the folder it's posting as the subject? If not, then what?

**Comment by peaveyman** [comment]
I figured it out. I leave the subject prefix blank and it will use the folder name as the subject. So now I can put all the folders I want to post in an upload folder and then use a wildcard to post them all without having to run sanguinews for each upload. Sweet deal. I think this can be closed.

**Comment by peaveyman** [comment]
It seems like using the wildcard it only uploaded the first folder in the upload folder. Is there a way to make it upload all the folders in the upload folder without having to run sanguinews separately for each folder?

**Comment by tdobrovolskij** [comment]
Sanguinews can either upload a directory or files. I never thought about uploading multiple directories at once, because for that particular task I have made [my rarnpar script](https://github.com/tdobrovolskij/rarnpar) and it could be easily scripted with bash one-liner anyway:
```bash
for i in $(ls); do sanguinews -v "$i" ; done
```
What about recursive mode? Not the behaviour your were looking for?

**Comment by peaveyman** [comment]
I'm not sure about recursive mode. What I do is copy the directories to an upload directory. Then I create the par files for each directory. I then name the folders with the scheme I need. So each folder will be named differently. Wouldn't recursive mode just upload each file with it's own name? If so, that wouldn't work for me.

As far as the rarnpar script, can it be made to just par? I don't need the rar as these are music files.

**Comment by tdobrovolskij** [comment]
My friend made a [guide for rarnpar some time ago which I posted on my site](https://tad-do.net/rarnpar/). It should help you with different use case scenarios. I don't remember what I've implemented there yet.
But if you need a simple upload of all the directories in your upload folder, then bash one-liner should do the job.

**Comment by peaveyman** [comment]
Thanks very much but as far as a bash one-liner, I would have no idea how to do that. I'm sort of a newb with it comes to that stuff. I will look at the guide for rarnpar. Thanks again.

**Comment by tdobrovolskij** [comment]
Well, sanguinews needs a guide like rarnpar has. But as with rarnpar, I am waiting till someone will write one and I will (re)post it then. :)
P.S. about the one-liner above: it will execute "sanguinews -v"(verbose directory upload) command for each and every non-hidden item in your current directory, but basically, because you are starting it with no "-f" flag, it will upload only directories there.

**Comment by peaveyman** [comment]
So your rarnpar script does the rar and par and run sanguinews to upload?

**Comment by tdobrovolskij** [comment]
Yes. Or newsmangler. Also has some advanced features. Everything(or almost everything) is explained in the guide I've mentioned above.

**Comment by peaveyman** [comment]
Then I gotta figure out how to use it. :) I can create the par files myself with pypar2 or with par2 from the command line but if I can run one command to do it all that would be great. I need to cut out the rar part of rarnpar, then par them, rename them to the naming sequence I need, then upload.

**Comment by peaveyman** [comment]
The one liner is doing the trick. It's uploading 3 folders now. Could something be added to it to to delete the folders after it's finished uploading?

Sorry for going off topic here.

**Comment by tdobrovolskij** [comment]
```bash
for i in $(ls) ; do [ -f "$i" ] && sanguinews -v -f "$i" ; [ -d "$i" ] && sanguinews -v "$i" ; rm -rf "$i" ; done
```
Upgraded version. It will check if $i is either file, or directory and execute sanguinews with the right options. Afterwards it will delete processed directory or file.

**Comment by peaveyman** [comment]
For some reason sanguinews won't upload. Just says unsuccessful. I know I have posting access because jbinup will post using the same credentials. Is there something I can look at?

**Comment by tdobrovolskij** [comment]
What options you have enabled there? It could say "Upload of chunk some_number is unsuccessful". It happens for various reasons and it's quite normal. Is the progress bar moving?

**Comment by peaveyman** [comment]
The only option I changed was the creation of the nzb file. I changed that to no. Yesterday it uploaded fine. The progress bar isn't moving, it never gets to the progress bar. It's going thru the files and everything is "Upload of chunk some_number is unsuccessful"

**Comment by tdobrovolskij** [comment]
Please enable debug mode in the .sanguinews.conf file:
```
debug = yes
```
And copy the output afterwards.

**Comment by peaveyman** [comment]
I have it enabled. Which output do you want?

**Comment by peaveyman** [comment]
I am seeing this output now "441 Posting Failed. Required "From" header is missing E1"

**Comment by tdobrovolskij** [comment]
So, it means that your "from" option is misconfigured. It should look like this example:
```
from = witty_nickname <whatever@example.com>
```
Notice the form: name <email>
It's required.

**Comment by peaveyman** [comment]
from = Peaveyman <News@Newsconnection.local>

Like that? That is what I have now in there.

**Comment by tdobrovolskij** [comment]
You did miss <> symbols.
I think, I'll be adding option validation soon, because I see how easy it can be to misconfigure something.

**Comment by peaveyman** [comment]
The <> are there, just didn't show in the comment.

**Comment by peaveyman** [comment]
Here is my config file.

https://ezcrypt.it/EBAn#XckyjwS75ALPfJgPfa3ffWz1

**Comment by tdobrovolskij** [comment]
Hm. I can upload files with a from field just like yours. It doesn't make much sense to me then. I'll need your debug output. Enable both "-v"(verbose mode) and debug mode. Wait for a minute to gather all possible error messages. Copy it, remove any private data and upload it somewhere or paste it here.

**Comment by peaveyman** [comment]
Here you go.

https://ezcrypt.it/FBAn#YIntK57TZGKIJU3STgu08bzs

**Comment by tdobrovolskij** [comment]
Well, it definitely looks like that your provider is unhappy with your email. Please try to change it to something more conventionally looking, like "example@gmail.com".

**Comment by peaveyman** [comment]
Nope, that didn't work either. And like I said, using the same "From" field jbinup is posting just fine. And sanguinews was working fine yesterday when I tried it.

**Comment by tdobrovolskij** [comment]
Ok, this is some strange bug. I would really like to help you, but I am trying to understand what is happening. Can you do one more thing? Open /home/gary/.gem/ruby/2.2.0/gems/sanguinews-0.80/lib/sanguinews/nntp_msg.rb in some text editor, go to line 45 and add between line 45 and 46:
```ruby
puts header
```
It should look like
```ruby
      sio.close
      puts header
      return header
```
Now the whole header will be printed out during the upload process. Copy and paste it please.

**Comment by peaveyman** [comment]
I can copy and paste the huge amount that it gave but I think this is what you want to see:

Encoding Charlie Lucas Band - Not Famous.log                                                                                                                         
From: 
Newsgroups: 
Subject: Charlie_Lucas-Not_Famous-Flac-2010 [1/27] - "Charlie Lucas Band - Not Famous.log" yEnc (1/1)
X-Newsposter: sanguinews v0.80 (ruby 2.2.0) - https://github.com/tdobrovolskij/sanguinews
Date: Sat, 07 Feb 2015 07:58:49 -0600

**Comment by peaveyman** [comment]
It seems to me it's not reading the .conf file right. I tried copying the sample file over and entering the info again but that didn't work either.

**Comment by tdobrovolskij** [comment]
I can not reproduce the bug. Just to be clear, the config file you are talking about is /home/gary/.sanguinews.conf ? With a dot in the beginning of file name(sorry, if question seems dumb, but you told me that you are new to unix), right? Yesterday it was working fine, so did you change anything?

**Comment by peaveyman** [comment]
Yes, the config is at /home/gary/.sanguinews.conf

I not totally new to unix just new to trying to write a bash script. And yes, it was working fine yesterday. And as far as I know I didn't change anything.
No such thing as a dumb question. :)

**Comment by tdobrovolskij** [comment]
Please list your local installed gems:
```
gem list
```
Also, considering that I have no more ideas at the moment, you could try to reinstall sanguinews:
```
gem uninstall sanguinews && gem install sanguinews
```

**Comment by peaveyman** [comment]
gem list

*** LOCAL GEMS ***

bigdecimal (1.2.6)
io-console (0.4.3)
json (1.8.1)
minitest (5.4.3)
nzb (0.2.2)
parseconfig (1.0.6)
power_assert (0.2.2)
psych (2.0.8)
rake (10.4.2)
rdoc (4.2.0)
sanguinews (0.80)
speedometer (0.1.3)
test-unit (3.0.8)

**Comment by peaveyman** [comment]
And the uninstall and reinstall didn't help. Still get the missing header error.

**Comment by tdobrovolskij** [comment]
Ok, gems have nothing to do with this. I see that you have the same version of gems which matter installed. *sigh*

So, we can only proceed with the remote debugging if you are still interested in tracking this bug down :)

Please open /home/gary/.gem/ruby/2.2.0/gems/sanguinews-0.80/lib/sanguinews/config.rb
Insert a new line between lines 31 and 32 with the following content:
```ruby
puts key.to_s + '=' + value.to_s
```
This part should look like:
```ruby
        value = config[key]
        puts key.to_s + '=' + value.to_s
        value = true if value == 'yes'
```
Start to upload something. You will get an output of your config file according to config processing method. Please remove the private data from this output and paste it here.

**Comment by peaveyman** [comment]
I am interested in tracking it down. Give me a few minutes and I will report back.

**Comment by peaveyman** [comment]
I did as you ask, where will the output be, in the terminal?

**Comment by tdobrovolskij** [comment]
Yes, in your terminal, just right at the top. It will look like your config file. If you see no output there, it means that the config file can not be opened by sanguinews. Maybe because of permissions, maybe because of something else.

**Comment by peaveyman** [comment]
groups=alt.binaries.sounds.flac,alt.binaries.sounds.lossless.country
from=Peaveyman <News@Newsconnection.local>
username=
password=
server=
ssl=yes
port=563
connections=20
article_size=768000
reconnect_delay=5
prefix=
nzb=no
header_check=no
debug=yes
xna=no
Encoding Charlie Lucas Band - Which Way To Turn.log                                                                                                                  
From: 
Newsgroups: 
Subject: Charlie_Lucas-Which_Way_To_Turn-Flac-2009 [1/26] - "Charlie Lucas Band - Which Way To Turn.log" yEnc (1/1)
X-Newsposter: sanguinews v0.80 (ruby 2.2.0) - https://github.com/tdobrovolskij/sanguinews
Date: Sat, 07 Feb 2015 09:14:23 -0600

**Comment by peaveyman** [comment]
I believe that's it

**Comment by tdobrovolskij** [comment]
OK, so the initial step is fine. it means that the data is being lost somewhere else. I will think where it could be. Will write back in a moment.

**Comment by peaveyman** [comment]
Ok, thanks for taking the time to do this.

**Comment by tdobrovolskij** [comment]
Ok, I think that I've found the bug. With disabled nzb creation not all parameters are being processed as they should. I will commit a patch in a matter of minutes. Thank you!

**Comment by peaveyman** [comment]
So disabling nzb creation caused the problem? No, thank you!

**Comment by tdobrovolskij** [comment]
Please reinstall the gem now. Version 0.80.1 fixes the issue.

**Comment by peaveyman** [comment]
Hot dog, you did it!!! Thanks so very much.

**Comment by tdobrovolskij** [comment]
Thank you for reporting this strange behaviour of my app! Looks like that no one else tried to upload with nzb creation disabled before.

**Comment by peaveyman** [comment]
Does the header check function work? I changed the conf file to make it check the headers and it wouldn't upload. I set it back to no and it's uploading again. Here is the error it gave:

No such article. Maybe server is lagging...(Careless - 01 - Careless.flac / Chunk: 12)                                                                               
Upload of chunk 12 from file Careless - 01 - Careless.flac unsuccessful. Retrying...                                                                                 
0.0KB/s^C/home/gary/.gem/ruby/2.2.0/gems/sanguinews-0.80.1/lib/sanguinews/thread-pool.rb:99:in `join': Interrupt                                                     
        from /home/gary/.gem/ruby/2.2.0/gems/sanguinews-0.80.1/lib/sanguinews/thread-pool.rb:99:in `map'
        from /home/gary/.gem/ruby/2.2.0/gems/sanguinews-0.80.1/lib/sanguinews/thread-pool.rb:99:in `shutdown'
        from /home/gary/.gem/ruby/2.2.0/gems/sanguinews-0.80.1/lib/sanguinews.rb:284:in `run!'
        from /home/gary/.gem/ruby/2.2.0/gems/sanguinews-0.80.1/bin/sanguinews:4:in `<top (required)>'
        from /home/gary/.gem/ruby/2.2.0/bin/sanguinews:23:in `load'
        from /home/gary/.gem/ruby/2.2.0/bin/sanguinews:23:in `<main>'

**Comment by tdobrovolskij** [comment]
It works as advertised - it makes your upload process slower(sometimes significantly), but it makes sure that the server will report "OK, I got it" for each chunk. So, if server is for some reason under a heavy load, it can take quite a long time. Just leave the upload process running for a longer time and you will see progress there.

**Comment by peaveyman** [comment]
I think I'm going to have to use it because I'm getting several chunks that aren't getting delivered for some reason.

**Comment by tdobrovolskij** [comment]
Few chunks shouldn't be a problem though, when you have par files included. But header check function can be useful when your provider is constantly loosing parts of your uploads.

**Comment by peaveyman** [comment]
It's more than a few chunks. On one from last night there was 10 out of 22 files that didn't make it and out of the 12 that did 3 weren't complete.

**Comment by peaveyman** [comment]
I'm using the header check function and it's uploaded the same picture 10 times so far.

**Comment by tdobrovolskij** [comment]
What do you mean by "the same picture"? It should re-upload the same chunk. Are you getting message that a file was uploaded more than once? If yes, it could mean that there is a bug in messaging/logging system, because files are checked and re-uploaded on a per chunk basis.
Anyway, if you are seeing re-upload message for 10 times already, it means that your provider's server is lagging quite badly. Maybe it's overloaded because of Sunday. Maybe this server is constantly in such state.

**Comment by peaveyman** [comment]
I'm seeing the same file on usenet 15 times that all say were just uploaded by me. But while this was going on in the terminal I was getting this:

https://ezcrypt.it/XBAn#dhDBHzTeBGYoIlZwMsVulObs

**Comment by tdobrovolskij** [comment]
The output seems fine. You are getting lots of garbage there because of debug output enabled, but otherwise everything is as it's supposed to be. I guess that file doubles which you are seeing is being caused by server lag. I never thought before that server lag is so common occurrence, but now I understand why other clients implement header checking the way they do. I'll redo it eventually too, in the future, by making it re-check files like 5-20 minutes after download is completed. Currently, NZB which is made will provide always with working download, without any doubles.

**Comment by peaveyman** [comment]
If I wanted to change value myself to make it wait longer where would I change it? Is it the check_delay in sanguinews.rb? The value is set to 4. If I wanted to make it wait 5 minutes what would I set it to?

**Comment by tdobrovolskij** [comment]
As I've explained above, now it works in seconds, not in minutes. The script is basically rechecking the server once in a while. It starts with 1 sec(normal, non lagging server will have everything by then). Next check will be in 5 seconds, if first was unsuccessful. Third - in 9, then 13 etc. Feel free to experiment with check_delay variable, if you feel that checks are being executed too often.
