### ISSUE TITLE
Error on Debian Jessie with ruby 2.0.0p247

### ISSUE THREAD

**Issue by hashworks** [tdobrovolskij/sanguinews#38]
```
$ sanguinews
/usr/local/lib/ruby/gems/2.0.0/gems/sanguinews-0.80.1/lib/sanguinews.rb:39: warning: Refinements are experimental, and the behavior may change in future versions of Ruby!
/usr/local/lib/ruby/gems/2.0.0/gems/sanguinews-0.80.1/lib/sanguinews.rb:55:in `<module:Sanguinews>': undefined method `using' for Sanguinews:Module (NoMethodError)
        from /usr/local/lib/ruby/gems/2.0.0/gems/sanguinews-0.80.1/lib/sanguinews.rb:54:in `<top (required)>'
        from /usr/local/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/lib/ruby/gems/2.0.0/gems/sanguinews-0.80.1/bin/sanguinews:2:in `<top (required)>'
        from /usr/local/bin/sanguinews:23:in `load'
        from /usr/local/bin/sanguinews:23:in `<main>'
```

Same result after updating all my gems.

**Comment by tdobrovolskij** [comment]
It looks like that refinements behave somehow differently with the version 2.0(I tested it on 2.1 and 2.2 MRI). I'll check what can possibly be done to solve it. Thanks for reporting it.
